version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: "echo python version"
          command: python -V
      - run:
          name: "check available packages"
          command: pip3 list
      - run:
          name: "Install required packages"
          command: pip3 install -r requirements.txt
      - run:
          name: "Install playright"
          command: playwright install
      - run:
          name: "Run test case"
          command: pytest test.py

workflows:
  test-execution:
    jobs:
      - build
